name = "emlinh-landingpage"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "emlinh-landingpage"

[env.preview]
name = "emlinh-landingpage-preview"

# Custom domains
[[env.production.custom_domains]]
binding = "emlinh-com"
domain_name = "emlinh.com"

[[env.production.custom_domains]]
binding = "www-emlinh-com"
domain_name = "www.emlinh.com"
